### ISSUE TITLE
Please add some annotation to the python script

### ISSUE THREAD

**Issue by NelloHo** [ianfab/FairyFishGUI#4]
To ianfab:
        Would you add some annotation to the python script , please ?
        I have some difficulty reading the code inside. Thank you.

**Comment by ianfab** [comment]
Hi, thanks for your interest in this project. Yes, the documentation is lacking since this was started as a quick proof of concept. I can try to add some comments over time, but if you have immediate questions feel free to ask them here or preferably on the Fairy-Stockfish discord https://discord.gg/FYUGgmCFB4 for a more real time communication.

**Comment by NelloHo** [comment]
Thanks !
